name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out repository code

    - uses: actions/setup-node@v3
      name: Set up Node.js
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint  # Make sure you have a lint script in package.json

    - name: Run tests
      run: npm test  # Make sure you have a test script in package.json

    - name: Any other checks
      run: echo "Add other checks here"

