name: Test Dependency Updates

on:
  pull_request:
    branches: [main]
    paths:
      - '**/package.json'
      - '**/yarn.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
