name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository code

      - uses: actions/setup-node@v3
        name: Set up Node.js
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Project
        run: npm run build  # You need to add a build script in your package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with the directory containing your built files
