name: Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows you to manually trigger the workflow from GitHub's UI

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out repository code

    - uses: actions/setup-node@v3
      name: Set up Node.js
      with:
        node-version: '20'  # Ensure this matches the version used for development

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build the project
      run: npm run build  # Replace this with your actual build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Replace with the directory of your build output
