name: Scheduled Maintenance Tasks

on:
  push:
    branches:
      - main

jobs:
  maintenance_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Replace with the version of Node.js you're using

      - name: Run maintenance script
        run: node ./scripts/maintenance.js
